#!/usr/bin/env bash
# Install claude-dev-team into ~/.claude/.
# Idempotent — safe to re-run.
set -euo pipefail

BUNDLE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_HOME="${CLAUDE_HOME:-$HOME/.claude}"
SKILL_DIR="$CLAUDE_HOME/skills/dev-team"
COMMANDS_DIR="$CLAUDE_HOME/commands"
SETTINGS_FILE="$CLAUDE_HOME/settings.json"
MARKER_FILE="$CLAUDE_HOME/.dev-team-installed"
VENV_DIR="$BUNDLE_DIR/.venv"
DT_PYTHON="$SKILL_DIR/dt-python"

VERSION="$(grep -m1 '^## ' "$BUNDLE_DIR/CHANGELOG.md" | sed -E 's/^## ([^ ]+).*/\1/')"

echo "claude-dev-team installer (version $VERSION)"
echo "  bundle:  $BUNDLE_DIR"
echo "  target:  $CLAUDE_HOME"
echo "  venv:    $VENV_DIR"
echo

# 1. Ensure dirs exist
mkdir -p "$SKILL_DIR" "$COMMANDS_DIR"

# 2. Create / refresh the bundle's Python venv and install adapter deps.
#    Bundle-owned venv lets us comply with PEP 668 (externally-managed envs
#    on modern Debian/Ubuntu) without --break-system-packages.
if ! python3 -m venv --help >/dev/null 2>&1; then
  echo "  ERROR: python3 -m venv is unavailable." >&2
  echo "         Install it first. On Debian/Ubuntu: sudo apt install python3-venv" >&2
  exit 1
fi

if [[ ! -x "$VENV_DIR/bin/python" ]]; then
  echo "  creating venv at $VENV_DIR"
  python3 -m venv "$VENV_DIR"
fi

echo "  upgrading pip in venv"
"$VENV_DIR/bin/pip" install --quiet --upgrade pip

echo "  installing adapter requirements into venv"
"$VENV_DIR/bin/pip" install --quiet -r "$BUNDLE_DIR/adapter/requirements.txt"

# 3. Write the dt-python wrapper so callers can invoke the venv python via
#    a stable path without knowing where the bundle was cloned.
cat > "$DT_PYTHON" <<EOF
#!/usr/bin/env bash
# dt-python — invoke the claude-dev-team bundle's venv Python.
# Generated by install.sh; regenerated on every re-run. Do not edit by hand.
exec "$VENV_DIR/bin/python" "\$@"
EOF
chmod +x "$DT_PYTHON"
echo "  wrote dt-python wrapper at $DT_PYTHON"

# 4. Symlink SKILL.md
ln -sf "$BUNDLE_DIR/SKILL.md" "$SKILL_DIR/SKILL.md"
echo "  linked SKILL.md"

# 5. Symlink the adapter/ dir so callers can reach scripts via the stable
#    ~/.claude/skills/dev-team/adapter/ path regardless of where the bundle
#    lives on disk.
ln -sfn "$BUNDLE_DIR/adapter" "$SKILL_DIR/adapter"
echo "  linked adapter/"

# 6. Symlink each slash command
for cmd in "$BUNDLE_DIR/commands/"*.md; do
  name="$(basename "$cmd")"
  ln -sf "$cmd" "$COMMANDS_DIR/$name"
done
echo "  linked $(ls "$BUNDLE_DIR/commands/" | wc -l) slash commands"

# 7. Symlink statusline.sh and ensure executable
ln -sf "$BUNDLE_DIR/hooks/statusline.sh" "$CLAUDE_HOME/statusline.sh"
chmod +x "$BUNDLE_DIR/hooks/"*.sh
echo "  linked statusline.sh"

# 8. Patch settings.json (idempotent)
# We use python here because shell-based JSON editing is fragile.
python3 - "$SETTINGS_FILE" "$BUNDLE_DIR" <<'PYEOF'
import json
import sys
from pathlib import Path

settings_path = Path(sys.argv[1])
bundle_dir = sys.argv[2]

if settings_path.exists():
    settings = json.loads(settings_path.read_text())
else:
    settings = {}

# StatusLine
settings.setdefault("statusLine", {})
settings["statusLine"]["type"] = "command"
settings["statusLine"]["command"] = f"{Path.home()}/.claude/statusline.sh"

# Hooks
hooks = settings.setdefault("hooks", {})

def upsert_hook(event_name, command, matcher=None):
    """Insert (or replace) a dev-team hook entry without disturbing others."""
    entries = hooks.setdefault(event_name, [])
    # Remove any existing dev-team entries for this event
    entries[:] = [e for e in entries if "dev-team" not in json.dumps(e)]
    entry = {
        "hooks": [
            {
                "type": "command",
                "command": command,
            }
        ]
    }
    if matcher is not None:
        entry["matcher"] = matcher
    entries.append(entry)

upsert_hook(
    "SessionStart",
    f"{bundle_dir}/hooks/session-start.sh",
)
upsert_hook(
    "PreToolUse",
    f"{bundle_dir}/hooks/phase-warn.sh",
    matcher="Edit|Write|Bash",
)

settings_path.parent.mkdir(parents=True, exist_ok=True)
settings_path.write_text(json.dumps(settings, indent=2) + "\n")
print(f"  patched {settings_path}")
PYEOF

# 9. Drop marker file
cat > "$MARKER_FILE" <<EOF
bundle_dir=$BUNDLE_DIR
version=$VERSION
installed_at=$(date -Iseconds)
EOF
echo "  marker: $MARKER_FILE"

echo
echo "Install complete."
echo
echo "Next steps:"
echo "  1. Restart Claude Code so it re-scans ~/.claude/commands/."
echo "  2. Run /dev-team-setup inside Claude Code to configure tokens."
echo "  3. cd into a project and run /dev-team-init or /dev-team-adopt."
